name: Build and Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Seoul
      
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Get current date (KST)
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

    - name: Add execute permission to gradlew
      run: chmod +x ./peterpet/gradlew

    - name: Build without Tests
      working-directory: peterpet
      run: ./gradlew build -x test

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      working-directory: peterpet
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }}

    - name: Deploy to Remote Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Cleanup old dangling or unused images
          docker image prune -af || true

          # Remove existing container
          docker stop peterpet || true
          docker rm peterpet || true

          # Remove existing image with same tag if exists
          docker rmi ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }} || true

          # Pull and run new container
          docker pull ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }}
          docker run -d --name peterpet -p 8080:8080 \
            -e MYSQL_MAIN_JDBC_URL="${{ secrets.MYSQL_MAIN_JDBC_URL }}" \
            -e MYSQL_MAIN_USERNAME="${{ secrets.MYSQL_MAIN_USERNAME }}" \
            -e MYSQL_MAIN_PASSWORD="${{ secrets.MYSQL_MAIN_PASSWORD }}" \
            -e GOOGLE_MAIL_USERNAME="${{ secrets.GOOGLE_MAIL_USERNAME }}" \
            -e GOOGLE_APP_PASSWORD="${{ secrets.GOOGLE_APP_PASSWORD }}" \
            -e CLOUD_AWS_REGION="${{ secrets.CLOUD_AWS_REGION }}" \
            -e CLOUD_AWS_BUCKET="${{ secrets.CLOUD_AWS_BUCKET }}" \
            -e CLOUD_AWS_CREDENTIALS_ACCESS_KEY="${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}" \
            -e CLOUD_AWS_CREDENTIALS_SECRET_ACCESS_KEY="${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_ACCESS_KEY }}" \
            -e TEST_SK_TESTKEY="${{ secrets.TEST_SK_TESTKEY }}" \
            -e TEST_CK_TESTKEY="${{ secrets.TEST_CK_TESTKEY }}" \
            -e GOOGLE_AI_IMAGE_KEY="${{ secrets.GOOGLE_AI_IMAGE_KEY }}" \
            -e DELIVERY_KEY="${{ secrets.DELIVERY_KEY }}" \
            -e CLIENT_ID="${{ secrets.CLIENT_ID }}" \
            -e CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
            -e KEY_PATH="${{ secrets.KEY_PATH }}" \
            ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }}
