name: Build and Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Add execute permission to gradlew
      run: chmod +x ./peterpet/gradlew

    - name: Build with Gradle
      working-directory: peterpet
      run: ./gradlew build

    - name: Log in to Docker Hub
      run: echo "${{ Secrets.DOCKER_PASSWORD }}" | docker login -u ${{ Secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ Secrets.DOCKER_USERNAME }}/my-app:latest .

    - name: Push Docker image
      run: docker push ${{ Secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Deploy to Remote Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ Secrets.SSH_HOST }}
        username: ${{ Secrets.SSH_USER }}
        key: ${{ Secrets.SSH_KEY }}
        script: |
          docker pull ${{ Secrets.DOCKER_USERNAME }}/my-app:latest
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 8080:8080 ${{ Secrets.DOCKER_USERNAME }}/my-app:latest
